name: Build on Windows

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Install dependencies
      shell: pwsh
      run: |
        pip3 install wheel
        pip3 install meson
        pip3 install ninja
        choco install yasm
        vcpkg.exe install pthread:x64-windows-static # it's requrired for one of dependencies of libvmaf
    - name: configure
      shell: pwsh
      run: |
        cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
    - name: make
      shell: pwsh
      run: |
        cd build
        nmake
